services:
  db:
    image: postgres:16.4
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=identity_go
    volumes:
      - ./sample-data/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
